#!/usr/bin/env bash
set -euo pipefail
SRC="${1:-$HOME/Movies/이_이미지를_바탕으로_천천히_화면이_돌아가는_동영상을.mp4}"
OUT="public/hero/frames"
TMP="$(mktemp -d)"
rm -rf "$OUT"; mkdir -p "$OUT" public/hero
cp "$SRC" public/hero/haeundae.mp4
ffmpeg -hide_banner -y -i "$SRC" -vf "fps=12,scale=1100:-1" "$TMP/f_%04d.png"
i=1
for f in "$TMP"/f_*.png; do
  printf -v n "%04d" "$i"
  cwebp -quiet -q 78 "$f" -o "$OUT/frame_$n.webp"
  i=$((i+1))
done
ffmpeg -hide_banner -y -ss 0 -i "$SRC" -frames:v 1 -update 1 -q:v 1 public/hero/poster.jpg
COUNT=$((i-1))
echo "frames: $COUNT"; du -sh "$OUT"
# emit the count as a TS constant the Hero imports
printf '// AUTO-GENERATED by scripts/build-hero-frames.sh — do not edit by hand.\nexport const HERO_FRAME_COUNT = %s;\n' "$COUNT" > lib/hero/frames.ts
rm -rf "$TMP"
